spring.application.name=discovery

server.port=8761

# THIS SERVER SHOULD NOT REGISTER ITSELF
eureka.client.register-with-eureka=false

# THIS SERVER SHOULD NOT FETCH REGISTRY
eureka.client.fetch-registry=false

management.info.env.enabled=true

info.app.name=discovery
info.app.version=1.0.0
info.app.description=Research Repository Discovery Service
